# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:$HOME/nextcloud/bin

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.zsh_history

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME=lukerandall
#ZSH_THEME=`cat .zshtheme | grep -v '^#' | head -1 | cut -f1`
ZSH_THEME=my

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git emacs python rsync sudo tmux command-not-found wd docker)
#plugins=(git emacs python rsync sudo tmux command-not-found wd docker man nmap ubuntu ufw z zsh-autosuggestions zsh-syntax-highlighting)
#plugins=(git emacs python rsync sudo tmux screen command-not-found wd docker man nmap ubuntu ufw z)
plugins=(git python sudo tmux command-not-found docker man nmap ufw z zsh-autosuggestions asdf)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias c="wl-copy"
alias v="wl-paste"

alias gs="git status"
alias gd="git diff"
alias gcsam="git commit -S -am"
alias gcsm="git commit -S -m"
alias gp="git pull"
alias gpu="git pushall"
alias gpa="git pushall"

alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '
alias chmox="chmod +x"

# the terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

alias e="nano"
alias se="sudo nano"
#https://stackoverflow.com/questions/10190358/how-to-use-emacsclient-on-root-files-using-sudo-and-a-single-daemon#10191436
#alias e="emacsclient -t -a=" #emacs
#alias se="SUDO_EDITOR='emacsclient -t -a=' sudoedit" #sudo emacs
#alias ew="emacsclient -c --no-wait -a=" #emacs window
#alias sew="SUDO_EDITOR='emacsclient -c -a=' sudoedit" #sudo emacs window
alias wcl="wc -l"
TMUX_SESSION_NAME=automagic
alias t="tmux attach -t $TMUX_SESSION_NAME || tmux new -s $TMUX_SESSION_NAME"
#alias t="tmux attach || tmux"
alias tdt="tmux detach"
alias s="screen -r||screen -q"
#alias n="nemo . &"
#alias sopen="gksu xdg-open"
#alias sudo='sudo '

#alias apt='sudo apt'
alias ins='sudo apt install'
alias rem='sudo apt autoremove --purge'
alias upd='sudo apt update;apt list --upgradeable'
alias upg='sudo apt upgrade;cat /var/run/reboot-required||echo "no restart needed :)"'
alias dupg='sudo apt dist-upgrade;cat /var/run/reboot-required||echo "no restart needed :)"'

#alias pacman=sudo pacman"
#alias ins="sudo pacman -Sy"
#alias rem="sudo pacman -Rdd"
#alias upd="sudo pacman -Syy"
#alias upg="sudo pacman -Syu"

#alias dnf="sudo dnf"
#alias ins="sudo dnf install"
#alias rem="sudo dnf remove"
#alias upd="sudo dnf check-update"
#alias upg="sudo dnf upgrade"

alias ll="ls -lah"
alias l="ls -lah"
unalias l
l(){
    cols=`tput cols`
    if [[ $# -eq 0 ]]; then
	      l .
    fi
    while [[ $# -ne 0 ]]; do
        printf '=%.0s' {1..$cols}
        echo
        if [[ -f "$1" ]]; then
            cat "$1"
        else
            ls -lAh "$1"
        fi
        printf '-%.0s' {1..$cols}
        echo
        ls -lAh -d "$1"
        shift
    done
}

open(){
    if [[ "$#" -eq 1 ]] && echo "$1" | grep "\.html$" > /dev/null; then
        #browser=`xdg-settings get default-web-browser`
	#kreadconfig5 --file /usr/share/applications/$browser --group "Desktop Action new-window" --key Exec
        #gtk-launch firedragon.desktop "$1" &
        #TODO get gtk-launch to open in a new window
        librewolf --new-window "$1" &
    else
        xdg-open $@ &
    fi
}

f(){
    #fm=nautilus
    #fm=nemo
    fm=dolphin
    if [[ $# == 0 ]]
    then
        $fm . &
    else
        $fm $@ &
    fi
}

wind(){
    find $@ | wc -l
}


activate(){
    source "$@/bin/activate"
}

#key bindings
#bindkey '^H' backward-kill-word
#bindkey -M emacs '^[[3;5~' kill-word
bindkey -M emacs '^[[3;3~' kill-word
#to find a key combo's code, run `cat`, then type the combo
#https://superuser.com/questions/997593/why-does-zsh-insert-a-when-i-press-the-delete-key

#autocomplete
setopt completealiases

#The program 'xyz' is not currently installed. You can install it by typing...
#. /etc/zsh_command_not_found

notica() { curl --data "d:$*" "https://notica.us/?gcbIuM" ; }
notica-web() {xdg-open "https://notica.us/?gcbIuM"}





# Keybindings section
bindkey -e
bindkey '^[[7~' beginning-of-line                               # Home key
bindkey '^[[H' beginning-of-line                                # Home key
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey "${terminfo[khome]}" beginning-of-line                # [Home] - Go to beginning of line
fi
bindkey '^[[8~' end-of-line                                     # End key
bindkey '^[[F' end-of-line                                     # End key
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey "${terminfo[kend]}" end-of-line                       # [End] - Go to end of line
fi
bindkey '^[[2~' overwrite-mode                                  # Insert key
bindkey '^[[3~' delete-char                                     # Delete key
bindkey '^[[C'  forward-char                                    # Right key
bindkey '^[[D'  backward-char                                   # Left key
bindkey '^[[5~' history-beginning-search-backward               # Page up key
bindkey '^[[6~' history-beginning-search-forward                # Page down key

# Navigate words with ctrl+arrow keys
bindkey '^[Oc' forward-word                                     #
bindkey '^[Od' backward-word                                    #
bindkey '^[[1;5D' backward-word                                 #
bindkey '^[[1;5C' forward-word                                  #
bindkey '^H' backward-kill-word                                 # delete previous word with ctrl+backspace
bindkey '^[[Z' undo                                             # Shift+tab undo last action

export LD_PRELOAD=""
export EDITOR="vim"
export PATH="$HOME/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/bin/core_perl:/usr/games/bin:$PATH"

# alias
#alias c="clear"
alias cur="curl --user-agent 'noleak'"
#alias l="ls -ahls --color=auto"
#alias r="reset"
#alias shred="shred -zf"
#alias sl="ls --color=auto"
alias vi="vim"
alias ls="ls --color=auto"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias wget="wget -c --user-agent 'noleak'"
alias dd="dd status=progress"
alias cp="cp -i"                          # confirm before overwriting something
alias rm="rm -i"
alias mv="mv -i"
alias df="df -h"                          # human-readable sizes
alias free="free -h"
alias du="du -h"

compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
setopt interactivecomments #allow comments in interactive shell mode
source ~/.config/sudo.plugin.zsh
compdef _doctl doctl

# opam configuration
[[ ! -r /home/user/.opam/opam-init/init.zsh ]] || source /home/user/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
