---
- name: set up framework
  hosts: localhost
  roles:
    - utils
    - environment
    - zsh
    - git
    - tmux
    # - wezterm
    - nethack
    - gnome-settings
    - framework-ssd-trim
    - huion-driver
    - gnome-extensions
#  tasks:
